fn main() {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "list_projects",
            "create_project",
            "list_project_tree",
            "read_diagram",
            "write_diagram",
            "get_project_diagram_config",
            "save_project_diagram_defaults",
            "save_diagram_overrides",
            "create_entry",
            "rename_entry",
            "move_entry_to_trash",
            "get_settings",
            "save_settings",
            "save_global_diagram_defaults",
            "list_ollama_models",
            "generate_diagram",
            "inspect_diagram_png",
            "save_diagram_png",
            "copy_diagram_png",
            "set_current_project",
            "get_current_project",
            "finish_quick_add",
            "cancel_quick_add",
        ]),
    ))
    .expect("failed to build Tauri application");
}
